{
  config,
  lib,
  flake,
  parsedArchToFlake,
  utils,
  pkgs,
  ...
}:
let
  inherit (flake.inputs.nix-snapshotter.packages.${flakeArchBuild}) nix-snapshotter;
  flakeArchBuild = parsedArchToFlake pkgs.stdenv.buildPlatform.parsed;
  mkLayer =
    {
      copyToRoot ? [ ],
      meta ? { },
      defaultDirMode ? "755",
      defaultDirUid ? 0,
      defaultDirGid ? 0,
    }:
    let
      # TODO: nixos modules merge system supports defining custom logic for merging options.
      # Maybe use it for the trees?
      mergeTrees =
        lhs: rhs:
        let
          f =
            path:
            lib.zipAttrsWith (
              n: v:
              let
                here = path ++ [ n ];
              in
              if lib.length v == 1 then
                lib.head v
              else
                let
                  lhs = lib.elemAt v 0;
                  rhs = lib.elemAt v 1;
                  assertions = [
                    {
                      # Directories generated by us don't have type field set
                      # until last step of building trees where we fill all entries that
                      # don't have type set with
                      # { type = "directory"; uid = defaultDirUid; gid = defaultDirGid; mode = defaultDirMode; }
                      assertion = lhs.type or "directory" == rhs.type or "directory";
                      message = "Can merge only directories";
                    }
                    (
                      let
                        l_uid = lhs.uid or defaultDirUid;
                        r_uid = rhs.uid or defaultDirUid;
                      in
                      {
                        assertion = (lhs ? "uid" && rhs ? "uid") -> l_uid == r_uid;
                        message = "UID mismatch (${toString l_uid} vs ${toString r_uid})";
                      }
                    )
                    (
                      let
                        l_gid = lhs.gid or defaultDirGid;
                        r_gid = rhs.gid or defaultDirGid;
                      in
                      {
                        assertion = (lhs ? "gid" && rhs ? "gid") -> l_gid == r_gid;
                        message = "GID mismatch (${toString l_gid} vs ${toString r_gid})";
                      }
                    )
                    (
                      let
                        l_mode = lhs.mode or defaultDirMode;
                        r_mode = rhs.mode or defaultDirMode;
                      in
                      {
                        assertion = (lhs ? "mode" && rhs ? "mode") -> l_mode == r_mode;
                        message = "Mode mismatch (${l_mode} vs ${r_mode})";
                      }
                    )
                  ];
                  failedAssertions = map (x: x.message) (lib.filter (x: !x.assertion) assertions);
                in
                lib.seq (
                  if lib.length failedAssertions > 0 then
                    throw ''
                      Assertions failed while merging fs trees:
                      ${lib.concatMapStringsSep "\n" (s: "- ${s}") failedAssertions}
                    ''
                  else
                    { }
                ) (f here v)
            );
        in
        f [ ] [ rhs lhs ];
      # Convert sequence of file entries into filesystem tree.
      # e.g.
      # [
      #   {type = "directory"; uid = 0; gid = 0; mode = "755"; path = "/"; };
      #   {type = "directory"; uid = 0; gid = 0; mode = "755"; path = "/run"; };
      #   {type = "directory"; uid = 0; gid = 0; mode = "755"; path = "/run/systemd"; };
      #   {type = "file"; uid = 0; gid = 0; mode = "644"; path = "/run/systemd/systemd-units-load"; contents = ""; };
      #   {type = "directory"; uid = 0; gid = 0; mode = "755"; path = "/usr/bin"; };
      #   ...
      # ]
      # into a tree structure (Nix attrsets):
      # {
      #   "/" = {
      #     type: "directory";
      #     uid = 0;
      #     gid = 0;
      #     mode = "755";
      #     children = {
      #       "run" = {
      #         type = "directory";
      #         uid = 0;
      #         gid = 0;
      #         mode = "755";
      #         children = {
      #           "systemd" = {
      #             type = "directory";
      #             uid = 0;
      #             gid = 0;
      #             mode = "755";
      #             children = {
      #               systemd-units-load = {
      #                 type = "file";
      #                 uid = 0;
      #                 gid = 0;
      #                 mode = "644";
      #                 contents = "";
      #               };
      #             };
      #           };
      #         };
      #       };
      #       "usr" = {
      #         # /usr directory is not present as part of input file list, but /usr/bin is.
      #         # In that case recursively create missing directories, setting theirs uid, gid, and mode properties
      #         # to defaultDirUid, defaultDirGid and defaultDirMode.
      #         type = "directory";
      #         uid = 0;
      #         gid = 0;
      #         mode = "755";
      #       };
      #     };
      #   };
      # }
      buildFsTree =
        list:
        let
          buildTree = lib.foldl' (
            acc: e:
            let
              mkTreeEntry =
                args@{ path, ... }:
                let
                  path' =
                    # must be absolute
                    assert lib.strings.hasPrefix "/" path;
                    lib.pipe path [
                      (lib.splitString "/")
                      (
                        components:
                        let
                          hasTrailingSlash = lib.last components == "";
                        in
                        {
                          inherit components hasTrailingSlash;
                        }
                      )
                      (
                        p:
                        p
                        // {
                          components = lib.filter (v: v != "") p.components;
                        }
                      )
                    ];
                  setByPath =
                    path: value:
                    let
                      len = lib.length path;
                      atDepth =
                        n:
                        if n == len then
                          value
                        else if n == len - 1 then
                          { ${lib.elemAt path n} = atDepth (n + 1); }
                        else
                          { ${lib.elemAt path n}.children = atDepth (n + 1); };
                    in
                    atDepth 0;
                in
                setByPath path'.components (lib.removeAttrs args [ "path" ]);

            in
            {
              children = mergeTrees (acc.children or { }) (mkTreeEntry e);
            }
          ) { };
          applyDefaults =
            let
              f =
                node:
                let
                  type = node.type or "directory";
                  uid = node.uid or defaultDirUid;
                  gid = node.gid or defaultDirGid;
                  mode = node.mode or defaultDirMode;
                in
                node
                // {
                  inherit
                    type
                    uid
                    gid
                    mode
                    ;
                  children = lib.mapAttrs (_: f) (node.children or { });
                };
            in
            f;
          applyMetadataOverrides =
            let
              f =
                path: value:
                g path value
                // {
                  children = lib.mapAttrs (n: f "${path}/${n}") (value.children or { });
                };
              g =
                path: value:
                let
                  path' = if path == "" then "/" else path;
                in
                if meta ? ${path'} then
                  value
                  // {
                    inherit (meta.${path'}) uid gid mode;
                  }
                else
                  value;
            in
            f "";
          checkAllMetadataApplied =
            tree:
            let
              knownPaths =
                let
                  f =
                    path: node:
                    lib.foldr (
                      { name, value }:
                      acc:
                      let
                        childPath = "${path}/${name}";
                      in
                      acc // (f childPath value)
                    ) (g (if path == "" then "/" else path) node) (lib.attrsToList (node.children or { }));
                  g = path: node: { ${path} = { }; };
                in
                f "" tree;
              notApplied = lib.pipe meta [
                (lib.filterAttrs (n: v: !(knownPaths ? ${n})))
                lib.attrNames
              ];
            in
            if lib.length notApplied > 0 then
              lib.warn ''
                Could not apply permissions to following files:
                ${lib.concatMapStringsSep "\n" (x: "- ${x}") notApplied}
              '' { }
            else
              { };
        in
        lib.pipe list [
          buildTree
          applyDefaults
          applyMetadataOverrides
          (v: lib.seq (checkAllMetadataApplied v) v)
        ];
      # Inverse of buildFsTree, convert tree into ordered list of entries, as expected by mklayer.
      fsTreeToList =
        tree:
        let
          f =
            path: node:
            lib.foldr (
              { name, value }:
              acc:
              let
                childPath = "${path}/${name}";
              in
              acc ++ (f childPath value)
            ) [ (g (if path == "" then "/" else path) node) ] (lib.attrsToList (node.children or { }));
          g = path: node: (removeAttrs node [ "children" ]) // { inherit path; };
        in
        f "" tree;
      getFileList =
        pkg:
        let
          file =
            pkgs.runCommand "${pkg.name}-file-list"
              {
                nativeBuildInputs = with pkgs; [ jq ];
              }
              ''
                cd ${pkg}
                while IFS= read -rd "" v; do
                  echo "$v" | jq -R -c '
                    split(":")  as $f |
                    {
                      type: {
                        "d": "directory",
                        "f": "regular",
                      }[$f[0]],
                      uid: 0,
                      gid: 0,
                      mode: $f[1],
                      path: "/" + ($f[2] | ltrimstr("./")),
                    }
                  ' >> $out
                done < <(find -mindepth 1 -printf "%y:%m:" -print0)
              '';
        in
        lib.pipe file [
          builtins.readFile
          (lib.splitString "\n")
          (lib.filter (x: x != ""))
          (map builtins.fromJSON)
          (map (e: e // { source = "${pkg}${e.path}"; }))
          buildFsTree
        ];
      filesFromCopyToRoot = lib.foldl' (acc: x: mergeTrees acc x) { } (map getFileList copyToRoot);
      mklayer = pkgs.callPackage ../../../packages/mklayer.nix { };
    in
    pkgs.runCommand "layer.tar"
      {
        nativeBuildInputs = [ mklayer ];
        passAsFile = [ "spec" ];
        spec = lib.pipe filesFromCopyToRoot [
          fsTreeToList
          (map builtins.toJSON)
          (lib.concatStringsSep "\n")
        ];
      }
      ''
        mklayer - --output $out < $specPath
      '';
  wrappersLayer = mkLayer {
    copyToRoot = [
      config.security.wrapperPackage
    ];
    meta = lib.listToAttrs (
      map (v: {
        name = v.file;
        value = {
          inherit (v) uid gid mode;
        };
      }) config.system.build.perms
    );
  };
  withLayers =
    { base, layers }:
    pkgs.runCommand base.name
      {
        nativeBuildInputs = with pkgs; [
          umoci
          jq
        ];
      }
      ''
        mkdir temp
        cd temp
        tar xf ${base}
        if [ ! -f oci-layout ]; then
          echo "No oci-layout" >&2
          exit 1
        fi

        temp="$(jq -r '.mediaType == "application/vnd.oci.image.index.v1+json" and .schemaVersion == 2' < index.json)"
        if [ "$temp" != "true" ]; then
          echo "Unsupported $(jq -r '.mediaType + " schema v" + (.schemaVersion | tostring)' < index.json) for index" >&2
          exit 1
        fi

        temp="$(jq -r '.manifests | length' < index.json)"
        if [ "$temp" != 1 ]; then
          echo "Expected exactly 1 manifest in the index" >&2
          exit 1
        fi

        tag="$(jq -r '.manifests.[].annotations."org.opencontainers.image.ref.name"' < index.json)"
        if [ "$tag" == "null" ]; then
          echo "Can't determine image tag" >&2
          exit 1
        fi

        ${lib.concatMapStringsSep "\n" (layer: "umoci raw add-layer --image \"$PWD:$tag\" ${layer}") layers}
        tar cf $out *
      '';
in
{
  options = {
    system.build.nix-snapshotter = lib.mkOption {
      type = lib.types.package;
      internal = true;
      readOnly = true;
    };
  };

  config = {
    system.build.nix-snapshotter = withLayers {
      base = nix-snapshotter.buildImage {
        name =
          if (config.system.nixos.containerName != null) then
            config.system.nixos.containerName
          else
            "nixos-${config.system.nixos.label}";
        tag = "latest";
        copyToRoot = [
          config.system.build.toplevel
          config.system.build.etc
        ];
        config = {
          cmd = [
            (utils.toShellPath config.users.users.root.shell)
            "--login"
          ];
          env = lib.mapAttrsToList (n: v: "${n}=${v}") config.environment.variables;
        };
      };
      layers = [
        wrappersLayer
      ];
    };
  };
}
